# ==========================================
# CREDENCIALES Y ENDPOINTS
# ==========================================
[api_scada]
url = "https://smartscada-api-sacmex.go-aigua.com:56443/api/Documents/tagviews/3e40f290-357d-40af-b706-9fc91017b29c/historic?nexustoken=d353530d-39ad-461d-9dcb-e4c864b65f3d"
token = "d353530d-39ad-461d-9dcb-e4c864b65f3d"

# ==========================================
# DICCIONARIO DE INFRAESTRUCTURA (UIDs)
# ==========================================
  [BUGAMBILIAS_Y_LOVELIA]
        "uid": "507382a9-d4e6-456e-aa21-e65277228eaa"
        "min": -0.21
        "max": 0.63
        "delegacion": "Xochimilco"
        "lat": 19.25178
        "lon": -99.10358
    
    [CDA_NINOS_HEROES]
        "uid": "c74fcf01-46ef-4963-a614-1e4f0893d180"
        "min": 0.0
        "max": 0.0
        "delegacion": "Xochimilco"
        "lat": 19.23202
        "lon": -99.12004
    
    [BENITO_JUAREZ_Y_CDA_IGNACION_ZARAGOZA]
        "uid": "ea90b142-e204-4fb1-9c6c-1421f5b0548b"
        "min": -0.02
        "max":  0.22
        "delegacion": "Xochimilco"
        "lat": 19.22977
        "lon": -99.12274
    
    [TEPEYAC_Y_GALEANA]
        "uid": "59341b02-313f-443b-8ab1-f7698ad48f10"
        "min": 0.04
        "max": 1.67
        "delegacion": "Xochimilco"
        "lat": 19.25059
        "lon": -99.05698
    
    [INSURGENTES_Y_VICENTE_GUERRERO]
        "uid": "dd1a4564-0e6f-4fb0-8d97-a1a391cc78c9"
        "min": 0.04
        "max": 1.68
        "delegacion": "Xochimilco"
        "lat": 19.25415
        "lon": -99.05834
    
    [MZ_68_LT_35]
        "uid": "ea479193-3a65-4208-83f5-067332b20be2"
        "min": 0.02
        "max": 1.03
        "delegacion": "Gustavo A Madero"
        "lat": 19.5655
        "lon": -99.13159
    
    [JAVIER_SOLIS_MZ_128_LT_28]
        "uid": "7683b452-f9af-416f-9c48-e6a49e99a1a7"
        "min": 2.74
        "max": 0.76
        "delegacion": "Iztapalapa"
        "lat": 19.34175
        "lon": -98.97919
    
    [CERRADA_PEDRO_INFANTE_MZ_150_LT3]
        "uid": "d9a555d2-a179-4ae3-8321-4cdf9e60042a"
        "min": -0.08
        "max": 4.68
        "delegacion": "Iztapalapa"
        "lat": 19.33905
        "lon": -98.9809
    
    [MIGUEL_ACEVES_MZ_4_LT_8]
        "uid": "68a5dbde-a219-4a36-b977-d1f3e011ff37"
        "min": 0.06
        "max": 4.05
        "delegacion": "Iztapalapa"
        "lat": 19.33861
        "lon": -98.98212
    
    [RETAMA_MZ_14_LT_1]
        "uid": "68eba353-6d85-4357-8869-88a8cfcda575"
        "min": 0.01
        "max": 1.48
        "delegacion": "Iztapalapa"
        "lat": 19.34663
        "lon": -99.01155
    
    [ANTIGUO_CAMINO_A_SANTIAGO_Y_AV_ACUEDUCTO]
	"uid": "e38bb8ad-b25e-4fca-aa0a-18361e0d42f8"
        "min": 2.6
        "max": 4.4
	"delegacion": "Xochimilco" 
        "lat": 19.24449 
        "lon": -99.11384
   
 [CAM_NACIONAL_Y_AV_ACUEDUCTO]
	"uid": "cc752116-e752-46c5-8372-84a5b5d7d802"
        "min": 2.0
        "max": 4.5
	"delegacion": "Xochimilco" 
        "lat": 19.2442 
        "lon": -99.11119      
  
 [CAMINO_NACIONAL_Y_7A_CDA_CAMINO_NACIONAL]
	"uid": "5498d482-ce91-4c1c-a59d-c8e854654718"
        "min": 2.25
        "max": 4.75
	"delegacion": "Xochimilco" 
        "lat": 19.24459 
        "lon": -99.11184      
  
 [LA_CANADA_Y_LA_CIMA]
	"uid": "4e415898-b598-4bb2-8c23-cc200aef372b"
        "min": 0.30
        "max": 0.40
	"delegacion": "Xochimilco" 
        "lat": 19.2386 
        "lon": -99.11877      
  
 [CDA_EMILIANO_ZAPATAY_1A_CDA_EMILIANO_ZAPATA]
	"uid": "4c8fb27b-5158-4a1d-8f6d-7d1c4af1dec6"
        "min": 0.29
        "max": 0.37
	"delegacion": "Xochimilco" 
        "lat": 19.238 
        "lon": -99.117      
  
 [DURAZNO_Y_MORA]
	"uid": "e3da87fc-bebf-445b-843a-ba5acae69ac5"
        "min": 0.0
        "max": 0.7
	"delegacion": "Xochimilco" 
        "lat": 19.23525 
        "lon": -99.11604      
  
 [CDA_NICOLAS_BRAVO_Y_CAM_ANTIGUO_A_SAN_ANDRES]
	"uid": "53a52146-93dd-43d8-8bb3-8bff76f4c513"
        "min": 0.0
        "max": 0.8
	"delegacion": "Xochimilco" 
        "lat": 19.23411 
        "lon": -99.11802      
  
 [PICHUCALCO_Y_SINANCHE]
	"uid": "c20d27f8-c46b-4573-9a41-494eb8a20c20"
        "min": -0.02
        "max":  0.0
	"delegacion": "Tlalpan" 
        "lat": 19.29372 
        "lon": -99.21763      
  
 [PICHUCALCO_Y_ACANCHE]
	"uid": "ce115215-458f-4021-8fe2-927bda45580c"
        "min": -0.01
        "max": -0.06
	"delegacion": "Tlalpan" 
        "lat": 19.29102 
        "lon": -99.21739      
  
 [POMUCH_Y_TIZIMIN]
	"uid": "b386e4e1-05dd-47f2-88e8-841d375eb97f"
        "min": 0.4
        "max": 1.8
	"delegacion": "Tlalpan" 
        "lat": 19.28855 
        "lon": -99.22852     
  
 [AKIL_Y_LABNA]
	"uid": "39841320-ced1-46f2-8afe-d354bb4a9d94"
        "min": 0.6
        "max": 0.9
	"delegacion": "Tlalpan" 
        "lat": 19.30182 
        "lon": -99.22336      
  
 [2A_CDA_TARASQUILLO_Y_CTO_NAHUI]
	"uid": "f07b55d5-8eeb-4e75-b11d-d024a691763b"
        "min": 0.0
        "max": 3.0
	"delegacion": "Tlalpan" 
        "lat": 19.28222 
        "lon": -99.24242      
 
  [CDA_BOKOBA_Y_TIXKOKOB]
	"uid": "ae29386d-4457-4327-9adc-40e9526bdccc"
        "min": 0.0
        "max": 0.1
	"delegacion": "Tlalpan" 
        "lat": 19.28368 
        "lon": -99.23026 
  
 [TIXKOKOB_Y_CELESTUM]
	"uid": "ae0fed95-78c2-407a-855e-b3d73830d6b0"
        "min": 0.0
        "max": 0.2
	"delegacion": "Tlalpan" 
        "lat": 19.27685 
        "lon": -99.2138 
  
 [DZIBALCHEN_Y_AKIL]
	"uid": "13c1601e-8739-4b03-bceb-aa605a071b51"
        "min": 0.0
        "max": 0.3
	"delegacion": "Tlalpan" 
        "lat": 19.27811 
        "lon": -99.22111
  
 [AV_35_Y_FERROCARRIL_DE_CUERNAVACA]
	"uid": "6598492b-89f4-4897-8b77-28bd2010072a"
        "min": 0.15
        "max": 0.16
	"delegacion": "Tlalpan" 
        "lat": 19.27468 
        "lon": -99.23195      
   
 [TEKAX_Y_GRECIA]
	"uid": "7ff9ea3c-8bae-4402-8e98-49bfb5875b94"
        "min": 0.0
        "max": 1.0
	"delegacion": "Tlalpan" 
        "lat": 19.27743 
        "lon":-99.22558       
  
 [AKIL_Y_CHANAL]
	"uid": "faf76448-401e-4124-82ca-b82808ad397e"
        "min": -0.02
        "max": 1.4
	"delegacion": "Tlalpan" 
        "lat": 19.2766 
        "lon": -99.22121      
  
 [JALAPA_Y_JALAPA]
	"uid": "d2f59bb2-9232-4a50-8b5c-1fb3f5f7f92f"
        "min": 0.5
        "max": 4.0
	"delegacion": "Magdalena Contreras" 
        "lat": 19.32177 
        "lon": -99.2242      
  
 [JALAPA_Y_TAMIAHUA]
	"uid": "c90e65d7-c749-4487-8ab3-daccc490b04d"
        "min": 2.0
        "max": 4.0
	"delegacion": "Magdalena Contreras" 
        "lat": 19.32124 
        "lon": -99.22587      
  
 [VERACRUZ_Y_AV_LUIS_CABRERA]
	"uid": "a03ef9b2-4305-464a-8e28-823642a273f4"
        "min": 3.95
        "max": 4.25
	"delegacion": "Magdalena Contreras" 
        "lat": 19.32029 
        "lon": -99.22804      
  
 [JALAPA_Y_NARANJOS]
	"uid": "df7ab7a9-304e-4592-8fe9-9817e71bcd72"
        "min": 1.6
        "max": 3.2
	"delegacion": "Magdalena Contreras" 
        "lat": 19.31898 
        "lon": -99.22859      
  
 [COATZACOALCOS_Y_FORTIN]
	"uid": "c0a76a67-e133-46c3-8e48-d69d68cc5859"
        "min": 1.0
        "max": 2.8
	"delegacion": "Magdalena Contreras" 
        "lat": 19.31713 
        "lon": -99.22776      
  
 [VERACRUZ_Y_AV_OAXACA]
	"uid": "3de353f7-be41-44ef-8a90-4a91f0a86047"
        "min": -0.07
        "max": 1.0
	"delegacion": "Magdalena Contreras" 
        "lat": 19.3153 
        "lon": -99.22571      
  
 [SONORA_Y_JALISCO]
	"uid": "de378b96-2bf0-4333-be8a-a0e68d33d8d2"
        "min": 2.4
        "max": 7.4
	"delegacion": "Magdalena Contreras" 
        "lat": 19.31406 
        "lon": -99.22547      
  
 [ZACATECAS_Y_AV_MEXICO]
	"uid": "7455a0b0-6c18-4527-a3ed-dfc6f09fcac9"
        "min": 1.0
        "max": 4.5
	"delegacion": "Magdalena Contreras" 
        "lat": 19.31265 
        "lon": -99.22551      
  
 [CIRCUITO_CUEMANCO_NTE_Y_AV_MUYUGUARDA]
	"uid": "2ad6267b-c2f9-4040-8158-c9f226ad9abc"
        "min": 0.6
        "max": 0.85
	"delegacion": "Xochimilco" 
        "lat": 19.28079 
        "lon": -99.11671      
  
 [CAMINO_REAL_A_XOCHITEPEC_Y_C5]
	"uid": "bb36a43c-e1cb-482e-8b46-156f0026663b"
        "min": 0.0
        "max": 1.8
	"delegacion": "Xochimilco" 
        "lat": 19.2646 
        "lon": -99.13496      
  
 [TEXMIOCA_Y_CDA_AGUSTIN_LARA]
	"uid": "7b462dbc-d8db-4f5a-985e-15de84e6daca"
        "min": 6.0
        "max": 12.0
	"delegacion": "Xochimilco" 
        "lat": 19.24746 
        "lon": -99.01583      
  
 [FLORICULTOR_Y_ACUEDUCTO]
	"uid": "81272669-c0c8-45b6-8d79-41a2dae73f5e"
        "min": 2.6
        "max": 3.5
	"delegacion": "Xochimilco" 
        "lat": 19.25506 
        "lon": -99.03752      
  
 [GOLONDRINA_Y_NACIONES_UNIDAS]
	"uid": "9ca1596d-bd07-45bf-8681-3474ad75210b"
        "min": 0.0
        "max": 1.0
	"delegacion": "Xochimilco" 
        "lat": 19.24744 
        "lon": -99.02732      
  
 [FRANCISCO_SARABIA_Y_22_DE_NOVIEMBRE]
	"uid": "0d2baa50-65b3-4c47-82a4-6be554a49b2e"
        "min": -1.0
        "max": 5.0
	"delegacion": "Xochimilco" 
        "lat": 19.2182 
        "lon": -99.09897      
  
 [CDA_GENERAL_MIGUEL_ENRIQUE_GUZMAN_Y_FRANCISCO_VILLA]
	"uid": "b768af95-32f0-4541-873a-196d70a8d6ae"
        "min": 0.0
        "max": 2.5
	"delegacion": "Xochimilco" 
        "lat": 19.24992 
        "lon": -99.02066      
 